app_service_plan_name = "ai-bot-restaurant"
bot_name              = "jhanvo"
location              = "East US"
open_ai_name          = "restaurantAI"
resource_group_name   = "ai-bot-restaurant-rg"
web_app_name          = "web-app-ai-bot-restaurant"